// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reset.sql

package database

import (
	"context"
)

const deleteUers = `-- name: DeleteUers :exec
DELETE FROM users
`

func (q *Queries) DeleteUers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUers)
	return err
}
